# Generated by Django 4.0.2 on 2022-02-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Processo:')),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('finalizado_em', models.DateField(verbose_name='Finaliza em:')),
                ('equipes', models.ManyToManyField(to='equipes.Equipes')),
            ],
        ),
    ]
