# Generated by Django 4.0.2 on 2022-02-04 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processos',
            name='equipes',
        ),
    ]
